sonar.projectKey=agriwizard
sonar.projectName=AgriWizard Smart Greenhouse
sonar.projectVersion=1.0

sonar.sources=services
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**

sonar.tests=services
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=services/*/coverage.out

sonar.sourceEncoding=UTF-8
